name: publish kaku-server

on:
  push:
    tags:
      - "server/[0-9]*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test
        working-directory: server

      - name: Publish
        run: npm publish --provenance
        working-directory: server
